include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    always_use_package_imports: true
    avoid_unused_constructor_parameters: true
    prefer_final_fields: true
    unawaited_futures: true
    prefer_asserts_in_initializer_lists: true
    sort_constructors_first: true
    use_named_constants: true
    prefer_single_quotes: true
